from automation_support import button, adbCmd, printMsg, setUp, \
    variables
from automation_support import TClogIn
import os
import time
from localUiautomator.uiautomator import device


def action():
    s = variables.s
    arr = []
    resp = []
    try:
        adbCmd.stopApp("mobi.hubbler.app")
        adbCmd.launchApp("mobi.hubbler.app", "StartActivity")
        print("\n\n")
        print("------event-------")
        button.menu().click()
        button.findText("Events").click()
        print("--events opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully in events")
        button.menu().click()
        button.findText("Events").click()
        button.backEventsPage().click()
        print("--app backbutton works successfully in events page")
        button.menu().click()
        button.findText("Events").click()
        button.active_pastEvent().click()
        button.pastEvent().click()
        print("--past event loads successfully")
        button.active_pastEvent().click()
        button.activeEvent().click()
        print("--active event loads successfully")
        button.eventCoverPicture().click()
        print("--event cover picture opens successfully")
        time.sleep(1)
        button.deviceBack()
        button.listView()[0].click()
        print("--Event opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully in event page")
        button.listView()[0].click()
        button.backEventDetailsPage().click()
        print("--app backbutton works successfully in event details page")
        button.listView()[0].click()
        button.optionsOnEvent().click()
        print("--optons on event opens successfully")
        print(button.listView().count)
        time.sleep(1)
        button.listView().child(index=1).click()
        print("--may be status clicked successfully")
        button.optionsOnEvent().click()
        button.listView().child(index=2).click()
        print("--not going status clicked successfully")
        button.optionsOnEvent().click()
        button.listView().child(index=0).click()
        print("--going status clicked successfully")
        button.invitePeople().click()
        print("--invite page opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully")
        button.invitePeople().click()
        button.backInvitePeoplePage().click()
        print("--app back button works successfully in invite people page")
        button.invitePeople().click()
        button.listView().scroll.vert.forward(steps=10)
        button.listView().scroll.vert.backward(steps=10)
        print("--scroll works successfully in invite page")
        button.backInvitePeoplePage().click()
        button.eventLocation().click()
        print("--event location opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--back button works successfully in ebent location page")
        button.eventLocation().click()
        button.backEventLocationPage().click()
        print("--app back button works successfully in event location page")
        button.eventStatusGoingPeopleList().click()
        print("--event status going list opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully in going list poage")
        button.eventStatusGoingPeopleList().click()
        button.backEventStatusPeopleList().click()
        print("--app back button works successfully in may be list page")
        button.eventStatusMaybePeopleList().click()
        print("--event status may be list opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully in may be list poage")
        button.eventStatusMaybePeopleList().click()
        button.backEventStatusPeopleList().click()
        print("--app back button works successfully in may be list page")
        button.invitedPeopleList().click()
        print("--event status invited list opens successfully")
        time.sleep(1)
        button.deviceBack()
        print("--device back button works successfully in invited list poage")
        button.invitedPeopleList().click()
        button.backEventStatusPeopleList().click()
        print("--app back button works successfully in invited list page")
        resp.append(True)
        resp.append(printMsg.printSuccess(os.path.basename(__file__)))
    except Exception as e:
        #         button.takeScreenShort(os.path.basename(__file__))
        resp.append(False)
        resp.append(printMsg.printException(e, os.path.basename(__file__)))
    return resp


if __name__ == "__main__":
    action()
